project:
  type: book
  output-dir: _book

book:
  title: "Elk River Watershed | Qukin ?amak?is Connectivity Restoration Plan: 2021 - 2041"
  author: "Canadian Wildlife Federation"
  date: last-modified
  date-format: "DD-MM-YYYY"
  chapters:
    - index.qmd
    - content/project-overview.qmd
    - content/glossary.qmd
    - content/methods.qmd
    - content/connectivity-status-ranking.qmd
    - content/workplan.qmd
    - content/references.qmd
    - content/version-history.qmd
  appendices: 
    - content/appendix-a.qmd
    - content/appendix-b.qmd


csl: csl/apa.csl


bibliography: references.bib
# nocite: |
#   @*

format:
  html:
    css: style.css
    theme: cosmo
    toc: false
    crossref:
      fig-title: '**Figure**'
      tbl-title: '**Table**'
  pdf: 
    toc: true
    toc-depth: 2
    documentclass: scrreprt
    colorlinks: true
  docx:
    toc: true
    number-sections: true
    highlight-style: github
    # reference-doc: custom-reference-doc.docx
    tbl-colwidths: [40, 30, 30]
    keep-md: true
    keep-ipynb: true

engine: knitr
#jupyter: "local-venv"

# execute:
#   cache: true

#titlepage-bg-image: images/spawn.jpg

title-block-banner: "#f6f6f6"